### ISSUE TITLE
Medprompt.py review

### ISSUE THREAD

**Issue by dkshjn** [Technoculture/Medprompt#11]
- ...
- ...

**Comment by sutyum** [comment]
What were the issues?

**Comment by dkshjn** [comment]
There was a dspy signature problem in the previous file so the chain of thoughts were getting generated in the incorrect format.

**Comment by dkshjn** [comment]
The current file works for the bigbio/med_qa dataset as the formatting is done accordingly but there seems to be some problem from the bigbio organization side as it's datasets are not getting loaded. So I will be adding the necessary changes for a few other datasets.
